#  POST http://127.0.0.1:8000/addtodo HTTP/1.1

# {
#     "item": "Turn into a dragon"
# }

# #

# GET http://127.0.0.1:8000/readtasks HTTP/1.1

#

PUT http://127.0.0.1:8000/edittodo HTTP/1.1

{
    "id": 0,
    "item": "turn into an electric dragon"
}
